name: bumpDocker
on:
  workflow_dispatch:
    inputs:
      bumpAmount:
        description: Bump amount
        required: true
        default: patch
        type: choice
        options:
          - patch
          - minor
          - major
jobs:
  bump:
    permissions:
      contents: write
    uses: jaid/workflows/.github/workflows/bump.yml@main
    with:
      bumpAmount: ${{ inputs.bumpAmount }}
  pushDocker:
    permissions:
      packages: write
      contents: read
    needs: bump
    strategy:
      fail-fast: false
      matrix:
        include:
          # - flavorSuffix: -debian
          #   image: debian:stable-slim
          #   arch: linux/amd64,linux/arm64/v8,linux/ppc64le,linux/s390x
          # - flavorSuffix: ''
          #   image: ubuntu:rolling
          #   arch: ''
          - flavorSuffix: -fast-build
            image: ubuntu:latest
            arch: linux/arm64/v8
          # - flavorSuffix: -ubuntu-latest
          #   image: ubuntu:latest
    uses: jaid/workflows/.github/workflows/pushDocker.yml@main
    with:
      buildArgs: image=${{ matrix.image }}
      flavorSuffix: ${{ matrix.flavorSuffix }}
      arch: ${{ matrix.arch }}
      additionalTags: ${{ needs.bump.outputs.newTag }}