name: bumpDocker
on:
  workflow_dispatch:
    inputs:
      bumpAmount:
        description: Bump amount
        required: true
        default: patch
        type: choice
        options:
          - patch
          - minor
          - major
jobs:
  job:
    strategy:
      fail-fast: false
      matrix:
        include:
          - flavorSuffix: -debian
            image: debian:stable-slim
            arch: linux/amd64,linux/arm64/v8,linux/ppc64le,linux/s390x
          - flavorSuffix: ''
            image: ubuntu:rolling
            arch: ''
          - flavorSuffix: -ubuntu-latest
            image: ubuntu:latest
    uses: jaid/workflows/.github/workflows/bumpDocker.yml@main
    with:
      bumpAmount: ${{ inputs.bumpAmount }}
      buildArgs: image=${{ matrix.image }}
      flavorSuffix: ${{ matrix.flavorSuffix }}
      arch: ${{ matrix.arch }}
    secrets:
      dockerHubToken: ${{ secrets.dockerHubToken }}
