name: bump
on:
  workflow_dispatch:
    inputs:
      bumpAmount:
        description: Bump amount
        required: true
        default: patch
        type: choice
        options:
          - patch
          - minor
          - major
jobs:
  debug:
    uses: ./.github/workflows/debug-overlay.yml
  job:
    name: ${{ github.workflow }}
    permissions:
      contents: write
    uses: ./.github/workflows/bump-overlay.yml
    with:
      bumpAmount: ${{ inputs.bumpAmount }}
