name: debug
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  job:
    uses: jaid/workflows/.github/workflows/debug.yml@main
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: installActionsToolkitNode
        shell: bash
        run: |
          npm install --global @actions/core
      - name: test
        shell: node {0}
        run: |
          console.log('moin')
