name: debug
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  job:
    uses: jaid/workflows/.github/workflows/debug.yml@main
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: setupNode
        uses: actions/setup-node@v3.6.0
        with:
          node-version: current
          cache: npm
      - name: installActionsToolkitNode
        shell: bash
        run: |
          npm install --global @actions/core
      - name: test
        shell: node {0}
        run: |
          console.log('moin')
          console.dir(require('@actions/core'))
