name: debug
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  job:
    uses: jaid/workflows/.github/workflows/debug.yml@main
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: setupNode
        uses: actions/setup-node@v3.6.0
        with:
          node-version: current
      - name: installActionsToolkitNode
        shell: bash
        run: |
          node --version
          npm --version
          which node
          which npm
          npm install --global @actions/core
      - name: test
        shell: bash -c "node --input-type module < {0}"
        run: |
          import a from "@actions/core"
          console.dir(a)
          console.log('moin')
