name: debug
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: env
        shell: bash
        run: |
          keys=($(printenv | cut -d'=' -f1))
          sortedKeys=($(printf '%s\n' "${keys[@]}" | tr ' ' '\n' | sort -df))
          for key in "${sortedKeys[@]}"; do
            declare value=$(printenv "$key")
            printf '%s=%s\n' "$key" "$value"
          done