name: debug
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  job:
    uses: jaid/workflows/.github/workflows/debug.yml@main
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: setupNode
        uses: actions/setup-node@v3.6.0
        with:
          node-version: current
      - name: installActionsToolkitNode
        shell: bash
        run: |
          node --version
          npm --version
          which node
          which npm
          npm install --global @actions/core
      - name: test
        shell: bash -o xtrace -c 'node --input-type module < {0}'
        run: |
          import "https://cdn.skypack.dev/pin/@actions/core@v1.10.0-UmNQL4zC8UQri7XWPAJq/mode=imports,min/optimized/@actions/core.js"
          console.log('moin')
