name: debug
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  job:
    uses: jaid/workflows/.github/workflows/debug.yml@main
  imageName:
    uses: jaid/docker-test/.github/workflows/getDockerImageName.yml@main