name: debug
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  job:
    uses: jaid/workflows/.github/workflows/debug.yml@main
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: akk
        uses: actions/setup-python@v4.5.0
        with:
          python-version: '3.11.2'
          cache: pip
      - name: installActionsToolkit
        shell: bash
        run: |
          pip install actions-toolkit
      - name: test
        shell: python
        run: |
          print("Hello world")
          from actions_toolkit import core
          for dist in __import__('pkg_resources').working_set:
            print(dist.project_name.replace('Python', ''))
