name: executePushDocker
on:
  workflow_call:
    inputs:
      passedInputs:
        type: string
        required: true
        description: JSON object containing all parent inputs
      matrixEntry:
        type: string
        required: true
        description: JSON object containing all matrix values
    secrets:
      dockerHubToken:
        required: false
        description: 'Create here with “Read, Write”: https://hub.docker.com/settings/security?generateToken=true'
    outputs:
      meta:
        value: ${{ jobs.push.outputs.meta }}
      digest:
        value: ${{ jobs.push.outputs.digest }}
      imageId:
        value: ${{ jobs.push.outputs.imageId }}
      imageName:
        value: ${{ jobs.push.outputs.imageName }}
      imageSlug:
        value: ${{ jobs.push.outputs.imageSlug }}
      imageUser:
        value: ${{ jobs.push.outputs.imageUser }}
run-name: invoke${{ inputs.nameSuffix }}
jobs:
  getInputs:
    name: getInputs${{ inputs.nameSuffix }}
    runs-on: ubuntu-latest
    outputs:
      value: ${{ steps.getInputs.outputs.value }}
    steps:
      - name: setupNode
        uses: actions/setup-node@v3.7.0
        with:
          node-version: latest
      - name: installNodePackages
        shell: bash
        run: npm install --no-save --no-package-lock @actions/core @actions/github lodash-es sort-keys prevent-start
      - id: getInputs
        name: getInputs
        shell: sh -c "node --input-type module < {0}"
        env:
          inputs: ${{ toJson(inputs) }}
        run: |
          import core from '@actions/core'
          import { context } from '@actions/github'
          import sortKeys from 'sort-keys'
          import {camelCase, omit} from 'lodash-es'
          import preventStart from 'prevent-start'
          const inputs = JSON.parse(process.env.inputs)
          const passedInputs = JSON.parse(inputs.passedInputs)
          const matrixEntry = JSON.parse(inputs.matrixEntry)
          console.dir({
            inputs,
            passedInputs,
            matrixEntry,
            context
          })
          const setOutput = (value, name = 'value') => {
            core.setOutput(name, value)
            core.info(`Output ${name}: ${value}`)
          }
          console.dir(omit(inputs, ['passedInputs', 'matrixEntry']))
          const outputs = {
            ...omit(inputs, ['passedInputs', 'matrixEntry']),
            ...passedInputs
          }
          for (const [key, value] of Object.entries(matrixEntry)) {
            const exclusiveKey = camelCase(`matrix ${key}`)
            outputs[exclusiveKey] = value
          }
          if (!outputs.imageName) {
            outputs.imageName = preventStart.default(context.payload.repository.name.toLowerCase(), 'docker-')
          }
          if (!outputs.imageUser) {
            outputs.imageUser = github.repository.owner.login.toLowerCase()
          }
          if (!outputs.imageSlug) {
            outputs.imageSlug = `${outputs.imageUser}/${outputs.imageName}`
          }
          if (!outputs.imageArtifact) {
            outputs.imageArtifact = `${github.run_id}_${outputs.matrixId}`
          }
          if (!outputs.imageFolder) {
            outputs.imageFolder = `/tmp/dockerBuild/${github.run_id}_${outputs.matrixId}`
          }
          if (!outputs.nameSuffix) {
            if (outputs.matrixId && outputs.matrixId !== 'default') {
              outputs.nameSuffix = ` (${outputs.matrixId})`
            } else {
              outputs.nameSuffix = ''
            }
          }
          for (const [key, value] of Object.entries(sortKeys(outputs))) {
            setOutput(value, key)
          }
          setOutput(JSON.stringify(outputs))
  # build:
  #   name: build${{ needs.getInputs.outputs.value.nameSuffix }}
  #   needs: getInputs
  #   uses: ./.github/workflows/buildDocker.overlay.yml
  #   with:
  #     id: ${{ needs.getInputs.outputs.value.matrixId }}
  #     arch: ${{ needs.getInputs.outputs.value.matrixPlatform }}
  #     buildContext: ${{ needs.getInputs.outputs.value.buildContext }}
  #     buildArgs: ${{ needs.getInputs.outputs.value.matrixBuildArgs }}
  #     imageName: ${{ needs.getInputs.outputs.value.imageName }}
  build:
    name: build${{ fromJson(needs.getInputs.outputs.value).nameSuffix }}
    needs: getInputs
    uses: ./.github/workflows/buildDocker.overlay.yml
    with:
      id: ${{ fromJson(needs.getInputs.outputs.value).matrixId }}
      arch: ${{ fromJson(needs.getInputs.outputs.value).matrixPlatform }}
      buildContext: ${{ fromJson(needs.getInputs.outputs.value).buildContext }}
      buildArgs: ${{ fromJson(needs.getInputs.outputs.value).matrixBuildArgs }}
      imageName: ${{ fromJson(needs.getInputs.outputs.value).imageName }}
  # test:
  #   if: ${{ needs.getInputs.outputs.value.matrixIsNativeArch }}
  #   name: test${{ inputs.nameSuffix }}
  #   needs:
  #     - getInputs
  #     - build
  #   uses: ./.github/workflows/testDocker.overlay.yml
  #   with:
  #     id: ${{ needs.getInputs.outputs.value.matrixId }}
  #     dockerRunArgs: ${{ needs.getInputs.outputs.value.testDockerRunArgs }}
  #     appArgs: ${{ needs.getInputs.outputs.value.testAppArgs }}
  #     testEval: ${{ needs.getInputs.outputs.value.testEval }}
  # push:
  #   name: push${{ matrix.id && format(' ({0})', matrix.id) }}
  #   needs:
  #     - getDockerImageName
  #     - makeMatrix
  #     - test
  #     - build
  #   permissions:
  #     packages: write
  #   strategy:
  #     matrix:
  #       include: ${{ fromJson(needs.makeMatrix.outputs.output) }}
  #   uses: ./.github/workflows/uploadDocker.overlay.yml
  #   with:
  #     id: ${{ matrix.id }}
  #     dockerHubUser: ${{ inputs.dockerHubUser }}
  #     dockerHubRegistry: ${{ inputs.dockerHubRegistry }}
  #     githubRegistry: ${{ inputs.githubRegistry }}
  #     baseTags: ${{ inputs.baseTags }}
  #     addShaTags: ${{ inputs.addShaTags }}
  #     addScheduleTags: ${{ inputs.addScheduleTags }}
  #     addVersionTag: ${{ inputs.addVersionTag }}
  #     versionTagPrefix: ${{ inputs.versionTagPrefix }}
  #     additionalTags: ${{ inputs.additionalTags }}
  #     versionTag: ${{ inputs.versionTag }}
  #     versionTagSemverPrefix: ${{ inputs.versionTagSemverPrefix }}
  #     flavorLatest: ${{ inputs.flavorLatest }}
  #     flavorPrefix: ${{ inputs.flavorPrefix }}
  #     flavorSuffix: ${{ inputs.flavorSuffix }}
  #     flavorConnectionString: ${{ inputs.flavorConnectionString }}
