on:
  workflow_call:
    inputs:
      imageName:
        type: string
        required: true
        description: If unset, the image name will be the repository name in lowercase
      dockerHubUser:
        type: string
        required: false
        description: If unset, the Docker Hub user will be the same as the GitHub user
    outputs:
      imageUser:
        description: The Docker Hub user
        value: ${{ jobs.job.outputs.imageUser }}
      imageName:
        description: The Docker image name
        value: ${{ jobs.job.outputs.imageName }}
      imageSlug:
        description: The Docker image slug
        value: ${{ jobs.job.outputs.imageSlug }}
jobs:
  job:
    name: getDockerImageName
    runs-on: ubuntu-latest
    outputs:
      imageUser: ${{ steps.getDockerHubUser.outputs.value }}
      imageName: ${{ steps.getDockerImageName.outputs.value }}
      imageSlug: ${{ steps.getDockerHubUser.outputs.value }}/${{ steps.getDockerImageName.outputs.value }}
    steps:
      - name: setupNode
        uses: actions/setup-node@v3.6.0
        with:
          node-version: current
      - name: installNodePackages
        shell: bash
        run: |
          npm install @actions/core @actions/github prevent-start
      - name: getDockerHubUser
        id: getDockerHubUser
        shell: sh -c "node --input-type module < {0}"
        env:
          inputs: ${{ toJSON(inputs) }}
        run: |
          import { context } from '@actions/github'
          import core from '@actions/core'
          const inputs = JSON.parse(process.env.inputs)
          const setOutput = (value, name = 'value') => {
            core.setOutput(name, value)
            core.info(`Output ${name}: ${value}`)
          }
          const dockerHubUser = inputs.dockerHubUser || context.payload.repository.owner.login
          setOutput(dockerHubUser)
      - name: getDockerImageName
        id: getDockerImageName
        shell: bash -c "node --input-type module < {0}"
        env:
          inputs: ${{ toJSON(inputs) }}
        run: |
          import { context } from '@actions/github'
          import core from '@actions/core'
          import preventStart from 'prevent-start'
          const inputs = JSON.parse(process.env.inputs)
          const setOutput = (value, name = 'value') => {
            core.setOutput(name, value)
            core.info(`Output ${name}: ${value}`)
          }
          if (inputs.imageName) {
            setOutput(inputs.imageName)
          } else {
            const output = preventStart.default(context.payload.repository.name.toLowerCase(), 'docker-')
            setOutput(output)
          }