name: pushDocker
on:
  push:
    branches:
      - main
  schedule:
    - cron: 45 23 * * 0 # https://crontab.guru/#45_23_*_*_0
jobs:
  job:
    uses: ./.github/workflows/pushDocker.overlay.yml
    permissions:
      contents: read
      packages: write
    with:
      dockerHubUser: jaidchen
      matrixPlatform: linux/amd64 linux/arm64/v8
      matrixBases: a b
      matrixFlavorEval: |
        const baseSegment = base === 'a' ? false : base
        const platformSegment = platformShortcuts[platform] ?? platform.replaceAll('/', '_')
        const flavor = [baseSegment, platformSegment].filter(part => part?.length).join('-')
      testEval: stdout.length > 0
    secrets:
      dockerHubToken: ${{ secrets.dockerHubToken }}